language: php

php:
  - 5.3.3

before_script:
  - composer self-update
  - composer update --prefer-source

script:
  - ./vendor/bin/phpunit -c ./tests/phpunit.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./src/

after_script:
  - php vendor/bin/coveralls -v