<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SamVersioning\Entity\VersionedObject'                  => __DIR__ . '/src/SamVersioning/Entity/VersionedObject.php',
    'SamVersioning\Entity\VersionedObjectInterface'         => __DIR__ . '/src/SamVersioning/Entity/VersionedObjectInterface.php',
    'SamVersioning\EventListener\VersioningListener'        => __DIR__ . '/src/SamVersioning/EventListener/VersioningListener.php',
    'SamVersioning\EventListener\VersioningListenerFactory' => __DIR__ . '/src/SamVersioning/EventListener/VersioningListenerFactory.php',
    'SamVersioning\Module'                                  => __DIR__ . '/src/SamVersioning/Module.php',
    'SamVersioning\Options\ConfigFactory'                   => __DIR__ . '/src/SamVersioning/Options/ConfigFactory.php',
    'SamVersioning\Service\VersioningService'               => __DIR__ . '/src/SamVersioning/Service/VersioningService.php',
    'SamVersioning\Service\VersioningServiceFactory'        => __DIR__ . '/src/SamVersioning/Service/VersioningServiceFactory.php',
    'SamVersioning\Service\VersioningServiceInterface'      => __DIR__ . '/src/SamVersioning/Service/VersioningServiceInterface.php',
);
